CC=clang++

f0=./main.cpp
f1=./js/js.cpp
f2=./js/engine/engine.cpp
f3=./js/engine/error/error.cpp
f4=./js/engine/error/tools/strings/strings.cpp
f5=./js/engine/parsing/parser.cpp
f6=./js/engine/parsing/parseTree/tree/tree.cpp
f7=./js/engine/parsing/parseTree/tree/noder/noder.cpp
f8=./js/engine/parsing/parseTree/tree/noder/formatter/formatter.cpp
f9=./js/engine/parsing/parseTree/tree/noder/operator/operator.cpp
f10=./js/engine/parsing/parseTree/tree/noder/recognizer/recognizer.cpp
f11=./js/engine/parsing/parseTree/tree/node/node.cpp
f12=./js/engine/parsing/parseTree/tree/node/classes/shared/attributes/attribute.cpp
f13=./js/engine/parsing/parseTree/tree/node/classes/shared/functions/function.cpp
f14=./js/engine/parsing/parseTree/tree/node/classes/array/array.cpp
f15=./js/engine/parsing/parseTree/tree/node/classes/tuple/tuple.cpp
f16=./js/engine/parsing/parseTree/tree/node/classes/boolean/boolean.cpp
f17=./js/engine/parsing/parseTree/tree/node/classes/null/null.cpp
f18=./js/engine/parsing/parseTree/tree/node/classes/string/string.cpp
f19=./js/engine/parsing/parseTree/tree/node/classes/object/object.cpp
f20=./js/engine/parsing/parseTree/tree/node/classes/undefined/undefined.cpp
f21=./js/engine/parsing/parseTree/tree/node/classes/number/number.cpp
f22=./js/engine/parsing/parseTree/tree/builder/builder.cpp
f23=./js/engine/lexing/lexer.cpp
f24=./js/engine/reducing/reducer.cpp

all: compile
compile:
	@${CC} -std=c++20 -g -o ./main.exe ${f0} ${f1} ${f2} ${f3} ${f4} ${f5} ${f6} ${f7} ${f8} ${f9} ${f10} ${f11} ${f12} ${f13} ${f14} ${f15} ${f16} ${f17} ${f18} ${f19} ${f20} ${f21} ${f22} ${f23} ${f24} 
	@./main.exe
