
CC=g++
f1=./main.cpp
f2=./jsClass/js.cpp
f3=./jsClass/engine/engine.cpp
f4=./jsClass/engine/error/error.cpp
f5=./jsClass/engine/error/tools/strings/strings.cpp

all: compile

compile:
	@${CC} -g -o ./main.exe ${f5} ${f1} ${f2} ${f3} ${f4}
	@./main.exe
