CC=clang++

f0=./main.cpp
f1=./jsClass/js.cpp
f2=./jsClass/engine/engine.cpp
f3=./jsClass/engine/error/error.cpp
f4=./jsClass/engine/error/tools/strings/strings.cpp
f5=./jsClass/engine/parsing/parser.cpp
f6=./jsClass/engine/parsing/parseTree/tree/tree.cpp
f7=./jsClass/engine/parsing/parseTree/tree/noder/noder.cpp
f8=./jsClass/engine/parsing/parseTree/tree/noder/helpers/helpers.cpp
f9=./jsClass/engine/parsing/parseTree/tree/node/node.cpp
f10=./jsClass/engine/parsing/parseTree/tree/node/classes/shared/attributes/attribute.cpp
f11=./jsClass/engine/parsing/parseTree/tree/node/classes/shared/functions/function.cpp
f12=./jsClass/engine/parsing/parseTree/tree/node/classes/array/array.cpp
f13=./jsClass/engine/parsing/parseTree/tree/node/classes/tuple/tuple.cpp
f14=./jsClass/engine/parsing/parseTree/tree/node/classes/boolean/boolean.cpp
f15=./jsClass/engine/parsing/parseTree/tree/node/classes/string/string.cpp
f16=./jsClass/engine/parsing/parseTree/tree/node/classes/object/object.cpp
f17=./jsClass/engine/parsing/parseTree/tree/node/classes/number/number.cpp
f18=./jsClass/engine/parsing/parseTree/tree/builder/builder.cpp
f19=./jsClass/engine/lexing/lexer.cpp
f20=./jsClass/engine/reducing/reducer.cpp

all: compile
compile:
	@${CC} -std=c++20 -g -o ./main.exe ${f0} ${f1} ${f2} ${f3} ${f4} ${f5} ${f6} ${f7} ${f8} ${f9} ${f10} ${f11} ${f12} ${f13} ${f14} ${f15} ${f16} ${f17} ${f18} ${f19} ${f20} 
	@./main.exe
